"""empty message

Revision ID: 22865f86671f
Revises: 3df07a84f43d
Create Date: 2024-05-06 21:04:20.328565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22865f86671f'
down_revision = '3df07a84f43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salaries',
    sa.Column('emp_no', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('emp_no', 'from_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salaries')
    # ### end Alembic commands ###
